### ISSUE TITLE
`'a option` generates `null`

### ISSUE THREAD

**Issue by simendsjo** [fscheck/FsCheck#215]
What is the best way to test `Option` values? I can use `obj.ReferenceEquals` to make sure the `Option` isn't null, but it just doesn't seem right.

```
// The type ''a option' does not have 'null' as a proper value
let f (x : 'a option) = isNull x

// Ok, passed 100 tests (99% <null>).
[<Property>]
let testOption (x : int option) =
    obj.ReferenceEquals(x, null) ==> Prop.collect x true
```

**Comment by ploeh** [comment]
If you expect the result of calling a function to be `None`, you compare against `None`. If you expect the result of calling a function to be `Some 42`, you compare against `Some 42`.

Option types have structural equality, so you simple compare the expected value against the actual value.

I suspect that I may not have answered your actual question, which I'll be happy to do if you can share an example of what you're actually trying to do :smile:

**Comment by ploeh** [comment]
Oh, I see now that you're attempting to filter `None` values away. Sorry, my fault :flushed:

**Comment by ploeh** [comment]
If I need an `int option` that's always `Some`, I usually ask for an `int` and explicitly wrap it in a `Some` case:

```F#
[<Property>]
let testOption (x : int) =
    let x' = Some x
    // rest of property goes here...
```

Often, I'd inline the `Some x` expression, in order to save a line of code (and a value name (`x'`)), but I hope you get the idea.

I find this a proper way to do this, because it makes it explicit to the reader of the test that this particular test case always uses the `Some` case, and not just any `int option`.

**Comment by kurtschelfthout** [comment]
`Option.isSome` and `Option.isNone` ?

**Comment by simendsjo** [comment]
I'm just testing FsCheck, so I can't find the exact experiment that triggered this, but I had some failing code when `'a option` was `null`. I'll see if I can find it at a later stage.

**Comment by ploeh** [comment]
The `None` case is `null` at run-time.

**Comment by simendsjo** [comment]
Might be related to `==>` or me misunderstanding it.

```
type T = {
    X : string option
}

[<Property>]
let ``If set has length gteq 0`` (t : T) =
    (t.X.IsSome && t.X.Value <> null) ==>
        let i = (t.X.Value.Length) // fails here, but shouldn't t.X be Some and the value be <> null?
        i >= 0
    |> Prop.collect t
```

```
System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
  ----> NUnit.Framework.AssertionException : Falsifiable, after 3 tests (0 shrinks) (StdGen (101390474,296142000)):
Original:
{X = null;}
with exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at FsLibCheck.Tests.If set has length gteq 0(T t) in C:\Users\simendsjo\code\ProjectScaffold\tests\FsLibCheck.Tests\Tests.fs:line 224
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at FsCheck.Runner.invokeAndThrowInner@310-1.Invoke(Object[] o) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck\Runner.fs:line 314
   at <StartupCode$FSharp-Core>.$Reflect.Invoke@961-4.Invoke(T1 inp)
   at FsCheck.Testable.evaluate[a,b](FSharpFunc`2 body, a a) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck\Testable.fs:line 161


   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at FsCheck.Runner.checkMethod(Config config, MethodInfo m, FSharpOption`1 target) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck\Runner.fs:line 318
   at FsCheck.NUnit.Addin.FsCheckTestMethod.runTestMethod(TestResult testResult) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck.NUnit.Addin\FsCheckTestMethod.fs:line 100
   at FsCheck.NUnit.Addin.FsCheckTestMethod.runTestCase(TestResult testResult) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck.NUnit.Addin\FsCheckTestMethod.fs:line 56
--AssertionException
   at NUnit.Framework.Assert.Fail(String message, Object[] args)
   at <StartupCode$FsCheck-NUnit-Addin>.$FsCheckTestMethod.testRunner@66.FsCheck-IRunner-OnFinished(String , TestResult ) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck.NUnit.Addin\FsCheckTestMethod.fs:line 86
   at FsCheck.Runner.check[a](Config config, a p) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck\Runner.fs:line 275

Falsifiable, after 3 tests (0 shrinks) (StdGen (101390474,296142000)):
Original:
{X = null;}
with exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at FsLibCheck.Tests.If set has length gteq 0(T t) in C:\Users\simendsjo\code\ProjectScaffold\tests\FsLibCheck.Tests\Tests.fs:line 224
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at FsCheck.Runner.invokeAndThrowInner@310-1.Invoke(Object[] o) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck\Runner.fs:line 314
   at <StartupCode$FSharp-Core>.$Reflect.Invoke@961-4.Invoke(T1 inp)
   at FsCheck.Testable.evaluate[a,b](FSharpFunc`2 body, a a) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck\Testable.fs:line 161
```

**Comment by kurtschelfthout** [comment]
F# has eager evaluation, so FsCheck can't prevent it from evaluating the right hand side of `==>` even if the left hand side is false. You should be able to wrap the right side in lazy to prevent this:

```
[<Property>]
let ``If set has length gteq 0`` (t : T) =
    (t.X.IsSome && t.X.Value <> null) ==>
        lazy (let i = (t.X.Value.Length) in i >= 0)
    |> Prop.collect t
```

**Comment by simendsjo** [comment]
Oh course! Thanks :)
The bug was in my head as usual.
