### ISSUE TITLE
Opaque error message?

### ISSUE THREAD

**Issue by haf** [fscheck/FsCheck#22]
Trying to use FsCheck with this code:

```
  let [<Fact>] ``serialising any`` () =
    let CanSerialiseAnyUnion (a : A) =
      let serialised = JsonConvert.SerializeObject(a, Formatting.Indented, List.toArray converters)
      let deserialised = JsonConvert.DeserializeObject(serialised, List.toArray converters)
      deserialised = a
    FsCheck.Check.Quick CanSerialiseAnyUnion
```

Where A is a discriminated union.

And I'm getting a strange error message:

```
Intelliplan.JsonNet.Tests.UnionConverterTests.serialising any [FAIL]
   System.InvalidCastException : Unable to cast object of type 'Arrow@204-2[Intelliplan.JsonNet.Tests.UnionConverterTests+A,System.Boolean]' to type 'Testable`1[Microsoft.FSharp.Core.FSharpFunc`2[Intelliplan.JsonNet.Tests.UnionConverterTests+A,System.Boolean]]'.
   Stack Trace:
      at Microsoft.FSharp.Core.LanguagePrimitives.IntrinsicFunctions.UnboxGeneric[T](Object source)
      at FsCheck.Runner.check[a](Config config, a p)
```

Can you help me interpret it?

**Comment by StachuK1992** [comment]
FYI - I just got this error now.
After changing .NET versions from 4.5.1 to 4.5.0 everywhere, it works. ¯\_(ツ)_/¯

**Comment by kurtschelfthout** [comment]
@StachuK1992 that leaves me very confused. Are you sure that doing that didn't somehow change the FSharp.Core version?

**Comment by kkm000** [comment]
Hi Kurt, I am also getting the same error with F# core 4.4 (no 2.0 references). Both tested library and test project are fresh off the mill under VS2015 and set .NET 4.5.2. Changing to 4.5.0 did not help.

```
Test Name:	NGramMutable.UnitTests.  SymbolTable reserves symbols
Test FullName:	NGramMutable.UnitTests.  SymbolTable reserves symbols
Test Source:	[snip]\test\grammars.unittest\Library1.fs : line 20
Test Outcome:	Failed
Test Duration:	0:00:00.108

Result StackTrace:	
at Microsoft.FSharp.Core.LanguagePrimitives.IntrinsicFunctions.UnboxGeneric[T](Object source)
   at FsCheck.Runner.check[a](Config config, a p) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck\Runner.fs:line 275
   at FsCheck.Check.One[Testable](Config config, Testable property) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck\Runner.fs:line 386
Result Message:	System.InvalidCastException : Unable to cast object of type 'Arrow@212-2[System.Int32,System.Boolean]' to type 'Testable`1[Microsoft.FSharp.Core.FSharpFunc`2[System.Int32,System.Boolean]]'.
```

Test:

```
[<Fact>]
let ``  SymbolTable reserves symbols``() =
   let testable n =  // <-- line 20
      let t = SymbolTable(n)
      t.Add("sym1") = n
   Check.QuickThrowOnFailure testable
```

What do you think can I try to figure why exactly it happens?

**Comment by kkm000** [comment]
And changing to 

```
[<Property>]
let ``  SymbolTable reserves symbols``(n : int) =
   let t = SymbolTable(n)
   t.Add("sym1") = n
```

ran the test just fine! Very strange indeed.

**Comment by kurtschelfthout** [comment]
Yes, puzzling. Though with FSharp.Core 4.4 you would need binding redirects. Are there any?

**Comment by kkm000** [comment]
Where the redirects for tests running inside visual studio should be? I do not know the whole architecture.

**Comment by kkm000** [comment]
> E.g. right after installation of FsCheck.Xunit it overrides FSharp.Core with version 4.3.1, from the FSharp.Core NuGet package.

I got rid of the package and reverted that fsproj change by editing the file, so I could easily change the version from the drop down.

**Comment by kkm000** [comment]
Debugging the failing test

```
'te.processhost.managed.exe' (CLR v4.0.30319: grammars.unittest): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\FSharp.Core\v4.0_4.4.0.0__b03f5f7f11d50a3a\FSharp.Core.dll'. Cannot find or open the PDB file.
[snip]
'te.processhost.managed.exe' (CLR v4.0.30319: grammars.unittest): Loaded 'C:\Users\kkm\AppData\Local\Temp\b8adb8e7-ae3b-493d-999d-1a9823798939\b8adb8e7-ae3b-493d-999d-1a9823798939\assembly\dl3\88e0823d\1340b31c_4747d101\FsCheck.dll'. Symbols loaded.
'te.processhost.managed.exe' (CLR v4.0.30319: grammars.unittest): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\FSharp.Core\v4.0_4.3.1.0__b03f5f7f11d50a3a\FSharp.Core.dll'. Cannot find or open the PDB file.
[snip]
Exception thrown: 'System.InvalidCastException' in FSharp.Core.dll
```

Looks like a redirect is required.

**Comment by kkm000** [comment]
I added the  redirect to the `App.config` of the unit test assembly itself, and that did the trick.

I was under an impression that redirects are honored only they are found in the config file of the initial executable. Good thing I was wrong! 

```
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="FSharp.Core" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.4.0.0" newVersion="4.4.0.0" />
      </dependentAssembly>
    </assemblyBinding>
```

**Comment by kurtschelfthout** [comment]
Yeah that works because of xunit - it picks up App.config of test dlls and adds their contents to the AppDomain it runs the tests in (or something along those lines). In other words it depends on the test runner you're using. I think for example NUnit 2.x does not do this, or at least not as reliably.

**Comment by kkm000** [comment]
Ah, so this is why it works! Thanks!
