### ISSUE TITLE
NullReferenceException stack trace with nothing related to my test code

### ISSUE THREAD

**Issue by smoothdeveloper** [fscheck/FsCheck#224]
Using 2.3 release, I hit this issue on call to Check.All
```
System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
  ----> System.NullReferenceException : Object reference not set to an instance of an object.

   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at FsCheck.Runner.checkMethod(Config config, MethodInfo m, FSharpOption`1 target) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck\Runner.fs:line 318
   at FsCheck.Runner.checkAll@326.Invoke(MethodInfo m) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck\Runner.fs:line 326
   at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source)
   at FsCheck.Runner.checkAll(Config config, Type t) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck\Runner.fs:line 327
   at UI.LineDiagram.Tests.OverlappingLabels.PropertyBasedTests.check all properties() in MYTESTS.fs:line 102
--NullReferenceException
   at Microsoft.FSharp.Text.StructuredPrintfImpl.Display.fit@519(Int32 maxWidth, FSharpFunc`2 leafFormatter, Breaks breaks, Int32 pos, Layout layout)
   at Microsoft.FSharp.Text.StructuredPrintfImpl.Display.fit@519(Int32 maxWidth, FSharpFunc`2 leafFormatter, Breaks breaks, Int32 pos, Layout layout)
   at Microsoft.FSharp.Text.StructuredPrintfImpl.Display.fit@519(Int32 maxWidth, FSharpFunc`2 leafFormatter, Breaks breaks, Int32 pos, Layout layout)
   at Microsoft.FSharp.Text.StructuredPrintfImpl.Display.fit@519(Int32 maxWidth, FSharpFunc`2 leafFormatter, Breaks breaks, Int32 pos, Layout layout)
   at Microsoft.FSharp.Text.StructuredPrintfImpl.Display.fit@519(Int32 maxWidth, FSharpFunc`2 leafFormatter, Breaks breaks, Int32 pos, Layout layout)
   at Microsoft.FSharp.Text.StructuredPrintfImpl.Display.fit@519(Int32 maxWidth, FSharpFunc`2 leafFormatter, Breaks breaks, Int32 pos, Layout layout)
   at Microsoft.FSharp.Text.StructuredPrintfImpl.Display.fit@519(Int32 maxWidth, FSharpFunc`2 leafFormatter, Breaks breaks, Int32 pos, Layout layout)
   at Microsoft.FSharp.Text.StructuredPrintfImpl.Display.fit@519(Int32 maxWidth, FSharpFunc`2 leafFormatter, Breaks breaks, Int32 pos, Layout layout)
   at Microsoft.FSharp.Text.StructuredPrintfImpl.Display.fit@519(Int32 maxWidth, FSharpFunc`2 leafFormatter, Breaks breaks, Int32 pos, Layout layout)
   at Microsoft.FSharp.Text.StructuredPrintfImpl.Display.fit@519(Int32 maxWidth, FSharpFunc`2 leafFormatter, Breaks breaks, Int32 pos, Layout layout)
   at Microsoft.FSharp.Text.StructuredPrintfImpl.Display.fit@519(Int32 maxWidth, FSharpFunc`2 leafFormatter, Breaks breaks, Int32 pos, Layout layout)
   at Microsoft.FSharp.Text.StructuredPrintfImpl.Display.fit@519(Int32 maxWidth, FSharpFunc`2 leafFormatter, Breaks breaks, Int32 pos, Layout layout)
   at Microsoft.FSharp.Text.StructuredPrintfImpl.Display.fit@519(Int32 maxWidth, FSharpFunc`2 leafFormatter, Breaks breaks, Int32 pos, Layout layout)
   at Microsoft.FSharp.Text.StructuredPrintfImpl.Display.fit@519(Int32 maxWidth, FSharpFunc`2 leafFormatter, Breaks breaks, Int32 pos, Layout layout)
   at Microsoft.FSharp.Text.StructuredPrintfImpl.Display.fit@519(Int32 maxWidth, FSharpFunc`2 leafFormatter, Breaks breaks, Int32 pos, Layout layout)
   at Microsoft.FSharp.Text.StructuredPrintfImpl.Display.fit@519(Int32 maxWidth, FSharpFunc`2 leafFormatter, Breaks breaks, Int32 pos, Layout layout)
   at Microsoft.FSharp.Text.StructuredPrintfImpl.Display.fit@519(Int32 maxWidth, FSharpFunc`2 leafFormatter, Breaks breaks, Int32 pos, Layout layout)
   at Microsoft.FSharp.Text.StructuredPrintfImpl.Display.fit@519(Int32 maxWidth, FSharpFunc`2 leafFormatter, Breaks breaks, Int32 pos, Layout layout)
   at Microsoft.FSharp.Text.StructuredPrintfImpl.Display.fit@519(Int32 maxWidth, FSharpFunc`2 leafFormatter, Breaks breaks, Int32 pos, Layout layout)
   at Microsoft.FSharp.Text.StructuredPrintfImpl.Display.fit@519(Int32 maxWidth, FSharpFunc`2 leafFormatter, Breaks breaks, Int32 pos, Layout layout)
   at Microsoft.FSharp.Text.StructuredPrintfImpl.Display.fit@519(Int32 maxWidth, FSharpFunc`2 leafFormatter, Breaks breaks, Int32 pos, Layout layout)
   at Microsoft.FSharp.Text.StructuredPrintfImpl.Display.fit@519(Int32 maxWidth, FSharpFunc`2 leafFormatter, Breaks breaks, Int32 pos, Layout layout)
   at Microsoft.FSharp.Text.StructuredPrintfImpl.Display.fit@519(Int32 maxWidth, FSharpFunc`2 leafFormatter, Breaks breaks, Int32 pos, Layout layout)
   at Microsoft.FSharp.Text.StructuredPrintfImpl.Display.squashTo(Int32 maxWidth, FSharpFunc`2 leafFormatter, Layout layout)
   at Microsoft.FSharp.Text.StructuredPrintfImpl.Display.layout_to_string(FormatOptions options, Layout layout)
   at Microsoft.FSharp.Core.PrintfImpl.Final1@224.Invoke(FSharpFunc`2 env, A a)
   at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 x)
   at FsCheck.Runner.argumentsToString@184-3.Invoke(FSharpList`1 x) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck\Runner.fs:line 184
   at FsCheck.Runner.onFailureToString[a](String name, TestData data, FSharpList`1 originalArgs, FSharpList`1 args, a usedSeed) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck\Runner.fs:line 200
   at FsCheck.Runner.onFinishedToString(String name, TestResult testResult) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck\Runner.fs:line 229
   at <StartupCode$FsCheck>.$Runner.get_throwingRunner@355.FsCheck-IRunner-OnFinished(String , TestResult ) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck\Runner.fs:line 365
   at FsCheck.Runner.check[a](Config config, a p) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck\Runner.fs:line 275
```

I don't have minimal reproduce case but my test looks like this (sorry I'm new to FsCheck, probably many things not optimal):

```fsharp
module PropertyBasedTests =
    open FsCheck
    open System

    /// this type defines random generator for various types
    type Generators =
      static member Bus() =
        { new Arbitrary<Bus>() with
            member __.Generator =
              gen {
                let! x, y = Gen.two Arb.generate<int>
                let! name = Gen.oneof [Arb.generate<string>]
                return Bus(null, Caption = name, Xcoord = x, Ycoord = y)
              }
        }
      static member SizeF() =
        { new Arbitrary<SizeF>() with
            member __.Generator =
              gen {
                let! x, y = Gen.two Arb.generate<float32>
                return SizeF(x, y)
              }
        }
    

    let ``should always call <= than count of buses`` b width height =
      (
        let floatOk v =
          [Single.IsInfinity; Single.IsNaN] 
          |> List.exists (fun p -> p v) 
          |> not

        (not (isNull buses))
        && floatOk width 
        && floatOk height 
      )
      ==>
        let size = SizeF(width, height)
        //(printfn "%A %A" size buses) |> ignore
        let count = Array.length buses
        let busesDrawn = ResizeArray<_>()
        let drawLabel = busesDrawn.Add
        frmLineDiagram.placeNodeLabels(buses, false, Func<_,_>(fun _ -> size), A drawLabel)
      
        count = busesDrawn.Count // i made this condition ill against my actual logic on purpose

    [<Test>]
    let ``check all properties`` () =
      Arb.register<Generators>() |> ignore
      let config = { FsCheck.Config.QuickThrowOnFailure with MaxTest = 500; MaxFail = 5000 }
      let propertiesContainerType = typeof<Generators>.DeclaringType // just a way to obtain typeof<PropertyBasedTests> but can't do that because it is a module
      Check.All(config, propertiesContainerType)
```

**Comment by kurtschelfthout** [comment]
Hard to say. Have you tried debugging and catching thrown exceptions?

Maybe `buses` is null? Where is that defined anyway, did you mean `b` instead?

**Comment by kurtschelfthout** [comment]
Is this still a problem? If so, can you post a working example (i.e. that compiles and runs without context). Thanks.

Going to close tomorrow due to inactivity otherwise...
