### ISSUE TITLE
Support Flags enums of types other than int

### ISSUE THREAD

**Issue by MartinJohns** [fscheck/FsCheck#299]
Hey, while trying to get into FsCheck I've noticed a weird behavior that caused me some headache. I believe it's a bug that occurs when you use the `FlagsAttribute`.

Used versions:

- FsCheck: 2.6.0
- FsCheck.Xunit: 2.6.0
- FSharpCore: 3.1.2.5

Example code:

```fsharp
open System
open FsCheck.Xunit

[<Flags>]
type MyFlags = One = 1uy | Two = 2uy

[<Property>]
let ``SomeTest`` (f: MyFlags) = true
```

Exception:

```
Exception during test
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at FsCheck.Runner.checkMethod(Config config, MethodInfo m, FSharpOption`1 target) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck\Runner.fs:line 318
   at FsCheck.Check.Method(Config config, MethodInfo methodInfo, FSharpOption`1 target) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck\Runner.fs:line 392
   at Xunit.Sdk.ExecutionTimer.Aggregate(Action action)
   at <StartupCode$FsCheck-Xunit>.$PropertyAttribute.testExec@187(PropertyTestCase this, IMessageBus messageBus, Object[] constructorArguments, CancellationTokenSource cancellationTokenSource, XunitTest test, RunSummary summary, TestOutputHelper outputHelper, Unit unitVar0) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck.Xunit\PropertyAttribute.fs:line 204
System.InvalidCastException: Specified cast is not valid.
   at FsCheck.ReflectArbitrary.v@30-1.Invoke(Enum x) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck\ReflectArbitrary.fs:line 30
   at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 x)
   at FsCheck.ReflectArbitrary.enumOfType@30.Invoke(FSharpList`1 els) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck\ReflectArbitrary.fs:line 30
   at <StartupCode$FsCheck>.$Gen.Map@26.Invoke(Int32 n, StdGen r) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck\Gen.fs:line 26
   at <StartupCode$FsCheck>.$Gen.Map@26.Invoke(Int32 n, StdGen r) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck\Gen.fs:line 26
   at FsCheck.GenBuilder.bind@66.Invoke(Int32 n, StdGen r0) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck\Gen.fs:line 67
   at FsCheck.Runner.test@105-1.GenerateNext(IEnumerable`1& next) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck\Runner.fs:line 116
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext()
   at FsCheck.Common.loop@63-1.GenerateNext(IEnumerable`1& next) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck\Common.fs:line 63
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext()
   at FsCheck.Common.takeWhilePlusLast@71.GenerateNext(IEnumerable`1& next) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck\Common.fs:line 72
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Collections.SeqModule.Fold[T,TState](FSharpFunc`2 folder, TState state, IEnumerable`1 source)
   at FsCheck.Runner.runner[a](Config config, a prop) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck\Runner.fs:line 163
   at FsCheck.Runner.check[a](Config config, a p) in C:\Users\Kurt\Projects\FsCheck\FsCheck\src\FsCheck\Runner.fs:line 275
``` 

It works when you remove the `[<Flags>]` attribute.

**Comment by kurtschelfthout** [comment]
FsCheck currently only supports ``Flags`` enums of type ``int``. So I'll update this report a bit to reflect that.

This would make a nice small-ish PR, if you or anyone is interested...

Code to change is here:  https://github.com/fscheck/FsCheck/blob/master/src/FsCheck/ReflectArbitrary.fs#L28-L32

The problem in particular is the cast to ``int`` on line 30, as the exception reports.
