### ISSUE TITLE
Gen computation expression builder throws NullRef on .NET Core.

### ISSUE THREAD

**Issue by teo-tsirpanis** [fscheck/FsCheck#372]
__project.fsproj__
``` xml
<Project Sdk="FSharp.NET.Sdk;Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="**/*.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FsCheck" Version="2.9.0" />
    <PackageReference Include="FsCheck.Xunit" Version="2.9.0" />
    <PackageReference Include="FSharp.Core" Version="4.1.*" />
    <PackageReference Include="FSharp.NET.Sdk" Version="1.0.*" PrivateAssets="All" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />
    <PackageReference Include="SoftWx.Numerics.Portable" Version="2.2.0" />
    <PackageReference Include="xunit" Version="2.2.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.2.0" />
  </ItemGroup>
</Project>
```
__Tests.fs__
``` fsharp
module Tests

open System
open Xunit
open FsCheck
open FsCheck.Xunit
open SoftWx.Numerics

let genUInt128 = Arb.generate<uint64> |> Gen.two |> Gen.map UInt128
let rec shrinkUInt128 x = seq {
    if x <> UInt128.Zero then
        let x = x - UInt128.One
        yield x
        yield! shrinkUInt128 x
}

type UInt128Generator =
    static member UInt128() = Arb.fromGenShrink (genUInt128, shrinkUInt128)

[<Property(Arbitrary = [|typeof<UInt128Generator>|])>]
let ``a * 1 = a`` x = x * UInt128.One = x
```

__dotnet test__
```
Build started, please wait...
Build completed.

Test run for c:\code\fscheck_bug\bin\Debug\netcoreapp1.1\fscheck_bug.dll(.NETCoreApp,Version=v1.1)
Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:02.6966837]   Discovering: fscheck_bug
[xUnit.net 00:00:02.9653533]   Discovered:  fscheck_bug
[xUnit.net 00:00:03.0428051]   Starting:    fscheck_bug
[xUnit.net 00:00:03.8103598]     Tests.a * 1 = a [FAIL]
[xUnit.net 00:00:03.8124288]       System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
[xUnit.net 00:00:03.8126015]       ---- System.NullReferenceException : Object reference not set to an instance of an object.
[xUnit.net 00:00:03.8147943]       Stack Trace:
[xUnit.net 00:00:03.8178861]            at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
[xUnit.net 00:00:03.8181988]            at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
[xUnit.net 00:00:03.8183908]            at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[xUnit.net 00:00:03.8186492]            at FsCheck.Runner.checkMethod(Config config, MethodInfo m, FSharpOption`1 target)
[xUnit.net 00:00:03.8188497]            at <StartupCode$FsCheck-Xunit>.$PropertyAttribute.testExec@187(PropertyTestCase this, IMessageBus messageBus, Object[] constructorArguments, CancellationTokenSource cancellationTokenSource, XunitTest test, RunSummary summary, TestOutputHelper outputHelper, Unit unitVar0)
[xUnit.net 00:00:03.8191202]         ----- Inner Stack Trace -----
[xUnit.net 00:00:03.8192530]            at FsCheck.GenBuilder.bind[a,b](Gen`1 _arg1, FSharpFunc`2 k)
[xUnit.net 00:00:03.8193804]            at FsCheck.GenBuilder.delay@61.Invoke(Int32 n, StdGen r)
[xUnit.net 00:00:03.8195035]            at FsCheck.Runner.test@96-1.GenerateNext(IEnumerable`1& next)
[xUnit.net 00:00:03.8196327]            at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
[xUnit.net 00:00:03.8197577]            at FsCheck.Common.loop@53-1.GenerateNext(IEnumerable`1& next)
[xUnit.net 00:00:03.8198809]            at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
[xUnit.net 00:00:03.8200016]            at FsCheck.Common.takeWhilePlusLast@61.GenerateNext(IEnumerable`1& next)
[xUnit.net 00:00:03.8201520]            at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
[xUnit.net 00:00:03.8203047]            at Microsoft.FSharp.Collections.SeqModule.Fold[T,TState](FSharpFunc`2 folder, TState state, IEnumerable`1 source)
[xUnit.net 00:00:03.8204369]            at FsCheck.Runner.runner[a](Config config, a prop)
[xUnit.net 00:00:03.8205734]            at FsCheck.Runner.check[a](Config config, a p)
[xUnit.net 00:00:03.8230210]       Output:
[xUnit.net 00:00:03.8232341]         Exception during test
[xUnit.net 00:00:03.8608959]   Finished:    fscheck_bug
Failed   Tests.a * 1 = a
Error Message:
 System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
---- System.NullReferenceException : Object reference not set to an instance of an object.
Stack Trace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at FsCheck.Runner.checkMethod(Config config, MethodInfo m, FSharpOption`1 target)
   at <StartupCode$FsCheck-Xunit>.$PropertyAttribute.testExec@187(PropertyTestCase this, IMessageBus messageBus, Object[] constructorArguments, CancellationTokenSource cancellationTokenSource, XunitTest test, RunSummary summary, TestOutputHelper outputHelper, Unit unitVar0)
----- Inner Stack Trace -----
   at FsCheck.GenBuilder.bind[a,b](Gen`1 _arg1, FSharpFunc`2 k)
   at FsCheck.GenBuilder.delay@61.Invoke(Int32 n, StdGen r)
   at FsCheck.Runner.test@96-1.GenerateNext(IEnumerable`1& next)
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at FsCheck.Common.loop@53-1.GenerateNext(IEnumerable`1& next)
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at FsCheck.Common.takeWhilePlusLast@61.GenerateNext(IEnumerable`1& next)
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at Microsoft.FSharp.Collections.SeqModule.Fold[T,TState](FSharpFunc`2 folder, TState state, IEnumerable`1 source)
   at FsCheck.Runner.runner[a](Config config, a prop)
   at FsCheck.Runner.check[a](Config config, a p)Standard Output Messages:
 Exception during test

Total tests: 1. Passed: 0. Failed: 1. Skipped: 0.
Test Run Failed.
Test execution time: 6,0189 Seconds
```

**Comment by kurtschelfthout** [comment]
Bizarrely it seems like the gen computation expression builder does not work on .NET core. Even:

```fsharp
[<Fact>]
let sample() = 
    genUInt128 |> Gen.sample 10 10 |> ignore
```

throws.

**Comment by eugene-g** [comment]
It is not FsCheck issue. See [this issue](https://github.com/dotnet/netcorecli-fsc/issues/79) for details.

Workaround: convert value to function (`let genUInt128 =` -> `let genUInt128 () =`) or add entrypoint to your test project, like this:
```
// HACK: fixes value initialization
// https://github.com/dotnet/netcorecli-fsc/issues/79
module Program = let [<EntryPoint>] main _ = 0
```

**Comment by kurtschelfthout** [comment]
Ah, great,, thanks for letting us know! I'll close this here then.

**Comment by teo-tsirpanis** [comment]
It works for me too. Thanks. 😃🎉
