### ISSUE TITLE
NullReferenceException in isCSharpDtoType

### ISSUE THREAD

**Issue by mausch** [fscheck/FsCheck#545]
`FsCheck.Check.QuickThrowOnFailure <| fun (u: System.UriBuilder) -> ()`

Crashes with:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at FsCheck.Reflect.getProperties@19.Invoke(PropertyInfo m)
   at Microsoft.FSharp.Collections.Internal.IEnumerator.next@193[T](FSharpFunc`2 f, IEnumerator`1 e, FSharpRef`1 started, Unit unitVar0) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 194
   at Microsoft.FSharp.Collections.Internal.IEnumerator.filter@188.System.Collections.IEnumerator.MoveNext() in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 196
   at Microsoft.FSharp.Collections.SeqModule.Exists[T](FSharpFunc`2 predicate, IEnumerable`1 source) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 531
   at FsCheck.Reflect.isCSharpDtoType(Type ty)
   at FsCheck.ReflectArbitrary.reflectObj(FSharpFunc`2 getGenerator, Type t)
   at FsCheck.ReflectArbitrary.reflectGenObj@142.Invoke(Type t)
   at FsCheck.Common.f@1[a,b](IDictionary`2 memo, FSharpFunc`2 f, a n, Unit _arg1)
   at FsCheck.Common.memoizeWith[a,b](IDictionary`2 memo, FSharpFunc`2 f, a n)
   at FsCheck.Common.memoize@22.Invoke(a n)
   at FsCheck.Arb.Derive@1296.get_Generator()
   at FsCheck.Testable.forAll[a,b](Arbitrary`1 arb, FSharpFunc`2 body)
   at FsCheck.Testable.Arrow@202-1.FsCheck-Testable-Testable`1-Property(FSharpFunc`2 f)
   at FsCheck.Runner.check[a](Config config, a p)
   at FsCheck.Check.QuickThrowOnFailure[Testable](Testable property)
   at <StartupCode$fschecktest>.$Program.main@()
```

Versions 2.14.3 and 3.0.0-alpha5

Tried to debug/fix it but I can't get the solution to build on Linux :-(

**Comment by kurtschelfthout** [comment]
Thanks. I'll fix it shortly. It's because there was a property that only had a setter, and so `propertyInfo.GetMethod` returns `null`.

Can you paste the output of running `build.sh` on Linux?

**Comment by kurtschelfthout** [comment]
Released in https://www.nuget.org/packages/FsCheck/2.14.4

**Comment by mausch** [comment]
Cheers for the quick fix!

> Can you paste the output of running build.sh on Linux?

My bad, I didn't notice it needs .net core _and_ also Mono.

**Comment by kurtschelfthout** [comment]
> My bad, I didn't notice it needs .net core and also Mono.

Yeah, 2.14 is an overly complicated build,  but since I'm working on 3.x at the moment I'm only planning to do bug fixes on 2.x. 

In 3.x the build uses only .net core and targets only netstandard 2.0. Makes things so much easier.
