### ISSUE TITLE
FsCheck.NUnit not compatible with NUnit 3.13.1

### ISSUE THREAD

**Issue by mvdfugro** [fscheck/FsCheck#551]
In NUnit 3.13.1 (pull request https://github.com/nunit/nunit/pull/3701) , Test.SetUpMethods / Test.TearDownMethods now return an NUnit-internal `NUnit.Framework.Interfaces.IMethodInfo[]` rather than `System.Reflection.MethodInfo[]`. This leads to a confusing

```
System.MissingMethodException : Method not found: 'System.Reflection.MethodInfo[] NUnit.Framework.Internal.Test.get_TearDownMethods()'.
   at FsCheck.NUnit.FsCheckTestMethod.RunTearDown(TestResult testResult)
   at FsCheck.NUnit.FsCheckTestMethod.RunTest(TestExecutionContext context) in C:\Users\kurts\Projects\FsCheck\FsCheck\src\FsCheck.NUnit\FsCheckPropertyAttribute.fs:line 108
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass4_0.<PerformWork>b__0()
   at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at NUnit.Framework.Internal.ContextUtils.DoIsolated(ContextCallback callback, Object state)
   at NUnit.Framework.Internal.ContextUtils.DoIsolated[T](Func`1 func)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork()
```

exception when trying to run a simple FsCheck test.

As a workaround, downgrading NUnit to 3.13.0 works fine.

**Comment by kurtschelfthout** [comment]
Just when I thought they had given up their wicked ways...anyway first thing to do is to restrict the compatible version range.

Then in further versions we can address the issue, and open up again.

**Comment by kurtschelfthout** [comment]
Released in https://www.nuget.org/packages/FsCheck.Nunit/2.14.6

**Comment by kurtschelfthout** [comment]
Released FsCheck.Nunit 2.15.0 which is compatible with NUnit 3.13.1.

**Comment by mvdfugro** [comment]
Thanks!
