### ISSUE TITLE
Wrong xUnit runner "xunit.execution.dotnet" chosen for .NET Framework property tests

### ISSUE THREAD

**Issue by ronnieholm** [fscheck/FsCheck#678]
If you create a new .NET 4.8 test project and reference 

- FsCheck.3.0.0-rc3
- FsCheck.Xunit.3.0.0-rc3
- xunit.2.7.0
- Other xUnit dependencies in 2.7.0 version

then the FsCheck `[<Property>]` test fails while the regular `[<Fact>]` test succeeds.

```fsharp
module FsCheckBug

open Xunit
open FsCheck.Xunit

[<Fact>]
let succeeds() =
    Assert.True(true)

[<Property>]
let fails() =
    Assert.True(true)
```

The failure is:

```
System.InvalidOperationException : Exception during discovery:
System.IO.FileNotFoundException: Could not load file or assembly 'xunit.execution.dotnet, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c' or one of its dependencies. The system cannot find the file specified.
File name: 'xunit.execution.dotnet, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c'
   at FsCheck.Xunit.PropertyDiscoverer.Xunit.Sdk.IXunitTestCaseDiscoverer.Discover(ITestFrameworkDiscoveryOptions discoveryOptions, ITestMethod testMethod, IAttributeInfo _arg1)
   at Xunit.Sdk.XunitTestFrameworkDiscoverer.FindTestsForMethod(ITestMethod testMethod, Boolean includeSourceInformation, IMessageBus messageBus, ITestFrameworkDiscoveryOptions discoveryOptions) in /_/src/xunit.execution/Sdk/Frameworks/XunitTestFrameworkDiscoverer.cs:line 119
   at Xunit.Sdk.XunitTestFrameworkDiscoverer.FindTestsForType(ITestClass testClass, Boolean includeSourceInformation, IMessageBus messageBus, ITestFrameworkDiscoveryOptions discoveryOptions) in /_/src/xunit.execution/Sdk/Frameworks/XunitTestFrameworkDiscoverer.cs:line 135
```

Two things stand out about the failure:

1. The test should've executed with `xunit.execution.desktop.dll`, not `xunit.execution.dotnet.dll` as the test project is a .NET Framework 4.8 project, not a .NET Core project.
2. The `2.4.1.0` version is wrong and should've been `2.7.0.0` as that's the version of the `xunit.extensibility.execution` NuGet package referenced.

Any tips on how to narrow down the cause?

**Comment by kurtschelfthout** [comment]
﻿﻿﻿﻿Maybe it’s the strong naming that causes trouble here.  I believe on newer .NET versions it’s handled automatically, but on framework you need an assembly redirect in a config file somewhere. This is compounded by figuring out how to make Xunit see that assembly redirect, as it does its one loading (ie there is no exe). Xunit docs may be some help there. On 2 Apr 2024, at 14:17, Ronnie Holm ***@***.***> wrote:﻿
Repro is available at https://github.com/ronnieholm/FsCheckWrongRunner
If you create a new .NET 4.8 test project and reference

FsCheck.3.0.0-rc3
FsCheck.Xunit.3.0.0-rc3
xunit.2.7.0
Other xUnit dependencies in 2.7.0 version

then in the same test class the FsCheck [property] test fails while the regular [Fact] test succeeds.
The failure is:
System.InvalidOperationException : Exception during discovery:
System.IO.FileNotFoundException: Could not load file or assembly 'xunit.execution.dotnet, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c' or one of its dependencies. The system cannot find the file specified.
File name: 'xunit.execution.dotnet, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c'
   at FsCheck.Xunit.PropertyDiscoverer.Xunit.Sdk.IXunitTestCaseDiscoverer.Discover(ITestFrameworkDiscoveryOptions discoveryOptions, ITestMethod testMethod, IAttributeInfo _arg1)
   at Xunit.Sdk.XunitTestFrameworkDiscoverer.FindTestsForMethod(ITestMethod testMethod, Boolean includeSourceInformation, IMessageBus messageBus, ITestFrameworkDiscoveryOptions discoveryOptions) in /_/src/xunit.execution/Sdk/Frameworks/XunitTestFrameworkDiscoverer.cs:line 119
   at Xunit.Sdk.XunitTestFrameworkDiscoverer.FindTestsForType(ITestClass testClass, Boolean includeSourceInformation, IMessageBus messageBus, ITestFrameworkDiscoveryOptions discoveryOptions) in /_/src/xunit.execution/Sdk/Frameworks/XunitTestFrameworkDiscoverer.cs:line 135

Two things stand out about the failure:

The test should've executed with xunit.execution.desktop.dll, not xunit.execution.dotnet as the test project is a .NET Framework 4.8 project, not a .NET Core project.
The 2.4.1.0 version is wrong and should've been 2.7.0.0 as that's the version of the xunit.extensibility.execution NuGet package referenced.

Any tips on how to narrow down the cause?

**Comment by ronnieholm** [comment]
> on framework you need an assembly redirect in a config file somewhere.

Indeed. I have other .NET Framework 4.8 test projects with xUnit and FsCheck where I need the following binding redirects in the test project's `App.config`.

```xml
<dependentAssembly>
    <assemblyIdentity name="xunit.core" publicKeyToken="8d05b1bb7a6fdb6c" culture="neutral" />
    <bindingRedirect oldVersion="2.2.0.0-2.4.2.0" newVersion="2.4.2.0" />
</dependentAssembly>
<dependentAssembly>
    <assemblyIdentity name="xunit.execution.desktop" publicKeyToken="8d05b1bb7a6fdb6c" culture="neutral" />
    <bindingRedirect oldVersion="2.2.0.0-2.4.2.0" newVersion="2.4.2.0" />
</dependentAssembly>
```

The above is from a test project running xUnit 2.4.2 and FsCheck 2.16.5. No problem with the `[Property]` attribute and discovery there.

For the Repro example, I've been using PerfView to trace assembly load events during test discovery and execution in VS. The following assemblies are getting loaded: 

![image](https://github.com/fscheck/FsCheck/assets/974199/c0e29814-314d-4e6c-a0c8-e0230adcd497)

Notice the highlighted one: `xunit.execution.desktop`, version 2.7.0.0 as expected for a .NET Framework project.

What makes xUnit attempt to load `xunit.execution.dotnet` into the process is a bit of mystery. It should be _either_ `xunit.execution.desktop` or `xunit.execution.dotnet`, I believe.

**Comment by ronnieholm** [comment]
From the results below, I'm not convinced the missing `xunit.execution.dotnet.dll` error is an issue with assembly redirects. Rather, it seems `FsCheck.Xunit.dll` is accidentally referencing `xunit.execution.dotnet.dll`.

I enabled Fusion logging and re-ran the test from the PowerShell terminal:

    $ & "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" C:\Users\rh\Desktop\FsCheckWrongRunner\bin\Debug\Repro.dll

It yielded the following output:

```
  Failed Repro.Class1.ShouldNotFail [1 ms]
  Error Message:
   System.InvalidOperationException : Exception during discovery:
System.IO.FileNotFoundException: Could not load file or assembly 'xunit.execution.dotnet, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c' or one of its dependencies. The system cannot find the file specified.
File name: 'xunit.execution.dotnet, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c'
   at FsCheck.Xunit.PropertyDiscoverer.Xunit.Sdk.IXunitTestCaseDiscoverer.Discover(ITestFrameworkDiscoveryOptions discoveryOptions, ITestMethod testMethod, IAttributeInfo _arg1)
   at Xunit.Sdk.XunitTestFrameworkDiscoverer.FindTestsForMethod(ITestMethod testMethod, Boolean includeSourceInformation, IMessageBus messageBus, ITestFrameworkDiscoveryOptions discoveryOptions) in /_/src/xunit.execution/Sdk/Frameworks/XunitTestFrameworkDiscoverer.cs:line 119
   at Xunit.Sdk.XunitTestFrameworkDiscoverer.FindTestsForType(ITestClass testClass, Boolean includeSourceInformation, IMessageBus messageBus, ITestFrameworkDiscoveryOptions discoveryOptions) in /_/src/xunit.execution/Sdk/Frameworks/XunitTestFrameworkDiscoverer.cs:line 135

=== Pre-bind state information ===
LOG: DisplayName = xunit.execution.dotnet, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c
 (Fully-specified)
LOG: Appbase = file:///C:/Users/rh/Desktop/FsCheckWrongRunner/bin/Debug
LOG: Initial PrivatePath = NULL
Calling assembly : FsCheck.Xunit, Version=3.0.0.0, Culture=neutral, PublicKeyToken=44dc6321e9b07168.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Users\rh\Desktop\FsCheckWrongRunner\bin\Debug\Repro.dll.config
LOG: Using host configuration file:
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Post-policy reference: xunit.execution.dotnet, Version=2.4.1.0, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c
LOG: Attempting download of new URL file:///C:/Users/rh/Desktop/FsCheckWrongRunner/bin/Debug/xunit.execution.dotnet.DLL.
LOG: Attempting download of new URL file:///C:/Users/rh/Desktop/FsCheckWrongRunner/bin/Debug/xunit.execution.dotnet/xunit.execution.dotnet.DLL.
LOG: Attempting download of new URL file:///C:/Users/rh/Desktop/FsCheckWrongRunner/bin/Debug/xunit.execution.dotnet.EXE.
LOG: Attempting download of new URL file:///C:/Users/rh/Desktop/FsCheckWrongRunner/bin/Debug/xunit.execution.dotnet/xunit.execution.dotnet.EXE.
```

Observe how the loader is attempting to locate `xunit.execution.dotnet.dll` in the `FsCheckWrongRunner/bin/Debug` folder. The file isn't there because the test project isn't a .NET project. The `xunit.execution.desktop.dll` on the other hand is present, copied there by MSBuild.

I then build `Repro.csproj` with binary logging enabled:

    $ msbuild /bl .\Repro.csproj

Inspecting the log with the MSBuild Structured Log Viewer, it contains unexpected entries like this one:

![image](https://github.com/fscheck/FsCheck/assets/974199/5e022027-aaf3-4e27-ae84-e1faad1023d7)

Notice at the bottom it says `Required by "FsCheck.Xunit" ...`. That's unexpected because according to the log `xunit.execution.desktop.dll` is _not_ required by `FsCheck.Xunit`.

To verify, I loaded `FsCheck.Xunit.dll` into dnSpy:

![image](https://github.com/fscheck/FsCheck/assets/974199/5cec3ee3-d963-4310-b776-9085314417cf)

Sure enough, `xunit.execution.dotnet` is a dependency of `FsCheck.Xunit.dll`.

I think this shouldn't be the case.

**Comment by kurtschelfthout** [comment]
That's indeed strange. Alpha 5 was the first version that used strong signing, perhaps that is related.

I have no idea how that dependency gets there either:

![image](https://github.com/fscheck/FsCheck/assets/164917/cce62ef1-9c79-431e-8049-b239098b5bd7)

**Comment by kurtschelfthout** [comment]
Oh wait. Needed to click one more open:

![image](https://github.com/fscheck/FsCheck/assets/164917/59f4abfb-494f-4004-8246-4c20a431ea53)

**Comment by kurtschelfthout** [comment]
Ok, from the xunit site:

```
xunit.extensibility.execution | This package contains the execution libraries for all Supports         (xunit.execution.*.dll). It is intended to be used by developers who wish         to reference this DLL for extensibility purposes, such as creating custom test discovery         and execution.                       It differs from the xunit.core package in that it adds a reference         to the platform specific execution DLL, rather than simply copying to the project's output folder.
```

So that seems to be the right thing for us to reference.

Perhaps these are not forward compatible with xunit 2.7 though.  If you downgrade xunit to 2.4 does it work?

**Comment by hglee** [comment]
I have same problem.

How about change `FsCheck.Xunit.fsproj` to multi target to `net452;netstandard2.0`?

https://github.com/fscheck/FsCheck/blob/0b2e2169ebe48cae87b1c529208e1c8fe5a0b229/src/FsCheck.Xunit/FsCheck.Xunit.fsproj#L5

**Comment by bash** [comment]
I am running into this same issue just now while trying to update [Funcky](https://github.com/polyadic/funcky/pull/812) to FsCheck 3.0.

@hglee's suggestion seems to work for me: I have tested the change to a multi-target locally.

**Comment by kurtschelfthout** [comment]
See https://github.com/xunit/xunit/discussions/2576

**Comment by kurtschelfthout** [comment]
released in 3.0.1
